version: '3'
services:
  ui:
    image: node:14
    container_name: react-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: npm start
    environment:
      - NODE_ENV=development